vse: &vse
  docker:
    - image: circleci/node:8.11.3
    - image: circleci/python:3.9.4

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *vse
     steps:
        - attach_workspace:
           at: .
        - run:
            name: Install Dependencies
            command: |
              python3 -m venv env
              . env/bin/activate
              pip install ansible
              pip install boto
              pip install boto3
              sudo apt update
        - run:
           command: |
             . env/bin/activate
             ansible-playbook ./ansible/ec2_deploy.yml
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master
