vse: &vse
  docker:
    - image: circleci/node:8.11.3
    - image: ansible/ansible:ubuntu1604

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *vse
     steps:
        - attach_workspace:
           at: .
        - run:
            name: Install System Packages
            command: pip install --upgrade pip && pip install ansible boto boto3
        - run:
           command: ansible-playbook ./ansible/ec2_deploy.yml
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master
